# VacationPy
----

#### Note
* Keep an eye on your API usage. Use https://developers.google.com/maps/reporting/gmp-reporting as reference for how to monitor your usage and billing.

* Instructions have been included for each segment. You do not have to follow them exactly, but they are included to help you think through the steps.

In [1]:
# Dependencies and Setup
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import requests
import gmaps
import os

# Import API key
from api_keys import g_key

### Store Part I results into DataFrame
* Load the csv exported in Part I to a DataFrame

In [2]:
csv_path = "/Users/Vanga/Desktop/Python_API_Challenge-/city_weather_df.csv"
city_weather_df = pd.read_csv(csv_path, encoding = "ISO-8859-1")
city_weather_df

,City,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Country,Date
0,Ushuaia,-54.8000,-68.3000,46.06,53,0,13.80,AR,1635648624
1,Arraial do Cabo,-22.9661,-42.0278,70.47,90,100,16.28,BR,1635648635
2,Kassala,15.4510,36.4000,80.35,39,0,6.98,SD,1635648635
3,BÃ¥tsfjord,70.6345,29.7185,36.66,84,99,9.91,NO,1635648635
4,Salalah,17.0151,54.0924,76.84,61,33,3.80,OM,1635648636
...,...,...,...,...,...,...,...,...,...
575,Katghora,22.5000,82.5500,71.38,48,85,6.06,IN,1635648799
576,Taylor,32.3001,-99.8337,68.72,43,1,5.01,US,1635648799
577,Warrnambool,-38.3833,142.4833,58.93,64,0,7.58,AU,1635648800
578,WaddÄn,29.1614,16.1390,65.70,40,58,3.76,LY,1635648800
579,Colesberg,-30.7200,25.0972,55.96,59,6,7.02,ZA,1635648800

### Humidity Heatmap
* Configure gmaps.
* Use the Lat and Lng as locations and Humidity as the weight.
* Add Heatmap layer to map.

In [3]:
# target_city = ""
# url = f"https://maps.googleapis.com/maps/api/geocode/json?address={target_city}&key={g_key}"
# geo_data = requests.get(url).json()
# print(geo_data)
locations = city_weather_df[["Lat", "Lng"]].astype(float)
humidity = city_weather_df["Humidity"].astype(float)
gmaps.configure(api_key=g_key)
fig = gmaps.figure()
hum_layer = gmaps.heatmap_layer(locations, weights=humidity, 
                                 dissipating=False, max_intensity=100,
                                 point_radius = 1)
fig.add_layer(hum_layer)
fig

Figure(layout=FigureLayout(height='420px'))

In [4]:
# ideal conditions: 
#     Max Weather > 65 < 80 
#     Wind Speed < 10 mph 
#     Cloudiness > 40 % 
#     Humidity < 75 %

### Create new DataFrame fitting weather criteria
* Narrow down the cities to fit weather conditions.
* Drop any rows will null values.

In [6]:
ideal_locations_df = city_weather_df.loc[(city_weather_df["Max Temp"]  >= 70)  &
                                         (city_weather_df["Max Temp"]  <  80)  &
                                         (city_weather_df["Wind Speed"] < 10) &
                                         (city_weather_df["Cloudiness"] < 40) &
                                         (city_weather_df["Humidity"] < 50)]
ideal_locations_df

,City,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Country,Date
11,Esperance,-33.8667,121.9000,78.64,40,2,4.56,AU,1635648638
162,San Patricio,28.0170,-97.5169,73.24,41,0,7.31,US,1635648681
273,Arlit,18.7369,7.3853,79.30,22,0,6.87,NE,1635648712
311,CastaÃ±os,26.7833,-101.4167,71.02,27,0,7.74,MX,1635648723
397,Los Andes,-32.8337,-70.5983,70.57,49,11,0.51,CL,1635648745
415,Fort Abbas,29.1925,72.8536,79.20,17,0,3.58,PK,1635648559
533,Kariba,-16.5167,28.8000,74.77,47,33,5.28,ZW,1635648787
542,PÄlanpur,24.1667,72.4333,74.61,32,18,3.85,IN,1635648789

### Hotel Map
* Store into variable named `hotel_df`.
* Add a "Hotel Name" column to the DataFrame.
* Set parameters to search for hotels with 5000 meters.
* Hit the Google Places API for each city's coordinates.
* Store the first Hotel result into the DataFrame.
* Plot markers on top of the heatmap.

In [7]:
hotel_df = ideal_locations_df
hotel_df["Hotel Name"] = ""

params = {
    "radius": 5000,
    "type": "lodging",
    "key": g_key,
}
for index, row in hotel_df.iterrows():
    base_url = "https://maps.googleapis.com/maps/api/place/nearbysearch/json"    
    lat = row["Lat"]
    lng = row["Lng"]
    params["location"] = f"{lat},{lng}"
    response = requests.get(base_url, params=params).json()
    results = response["results"]
    print(f"Retrieving results for Index {index}: {results[0]['name']}.")
    try: 
        hotel_df.loc[index, "Hotel Name"] = results[0]['name']
    except (KeyError, IndexError):
        print("Missing field/result...skipping")
    print("----------------------")

/var/folders/kq/kg5l2m0n5tqf0tjsyx81vs5c0000gn/T/ipykernel_7870/1703444650.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  hotel_df["Hotel Name"] = ""

Retrieving results for Index 11: Hospitality Esperance.
----------------------

/Users/Vanga/opt/anaconda3/envs/PythonData/lib/python3.8/site-packages/pandas/core/indexing.py:1817: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._setitem_single_column(loc, value, pi)

Retrieving results for Index 162: Motel 6 Sinton, TX.
----------------------
Retrieving results for Index 273: Case de Passage De la Prefecture.
----------------------
Retrieving results for Index 311: Bomberos voluntarios castaños coahuila.
----------------------
Retrieving results for Index 397: Hotel Los Andes.
----------------------
Retrieving results for Index 415: AsAd's House.
----------------------
Retrieving results for Index 533: Caribbea Bay Hotel.
----------------------
Retrieving results for Index 542: Hotel Lajwanti.
----------------------

In [8]:
hotel_df

,City,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Country,Date,Hotel Name
11,Esperance,-33.8667,121.9000,78.64,40,2,4.56,AU,1635648638,Hospitality Esperance
162,San Patricio,28.0170,-97.5169,73.24,41,0,7.31,US,1635648681,"Motel 6 Sinton, TX"
273,Arlit,18.7369,7.3853,79.30,22,0,6.87,NE,1635648712,Case de Passage De la Prefecture
311,CastaÃ±os,26.7833,-101.4167,71.02,27,0,7.74,MX,1635648723,Bomberos voluntarios castaños coahuila
397,Los Andes,-32.8337,-70.5983,70.57,49,11,0.51,CL,1635648745,Hotel Los Andes
415,Fort Abbas,29.1925,72.8536,79.20,17,0,3.58,PK,1635648559,AsAd's House
533,Kariba,-16.5167,28.8000,74.77,47,33,5.28,ZW,1635648787,Caribbea Bay Hotel
542,PÄlanpur,24.1667,72.4333,74.61,32,18,3.85,IN,1635648789,Hotel Lajwanti

In [9]:
# NOTE: Do not change any of the code in this cell

# Using the template add the hotel marks to the heatmap
info_box_template = """
<dl>
<dt>Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
</dl>
"""
# Store the DataFrame Row
# NOTE: be sure to update with your DataFrame name
hotel_info = [info_box_template.format(**row) for index, row in hotel_df.iterrows()]
hot_locations = hotel_df[["Lat", "Lng"]]

In [10]:
# Add marker layer ontop of heat map
fig = gmaps.figure()
markers = gmaps.marker_layer(hot_locations)
click_layer = gmaps.symbol_layer(
    hot_locations, fill_color='rgba(0, 150, 0, 0.4)',
    stroke_color='rgba(0, 0, 150, 0.4)', scale=2, info_box_content = hotel_info)

# Display figure
fig.add_layer(markers)
fig.add_layer(hum_layer)
fig.add_layer(click_layer)
fig

Figure(layout=FigureLayout(height='420px'))